usys=usrinit/usys.S
kextemp=syscall/ext.c
kfuntemp=syscall/fun.c
kstrtemp=syscall/str.c
ksys=src/syscall.c
sysnum=src/include/sysnum.h

echo "# generated by usys.pl - do not edit\n">>$usys;

echo "#include \"src/include/sysnum.h\"\n">>$usys;

echo "static uint64 (*syscalls[])(void) = {">>$kfuntemp;
echo "static char *sysnames[] = {">>$kstrtemp;

entry(){
    echo ".global $2">>$usys;
    echo "$2:">>$usys;
    echo "\tli a7, SYS_$2">>$usys;
    echo "\tecall">>$usys;
    echo "\tret">>$usys;
    echo "#define SYS_$2\t$1">>$sysnum
    echo "extern uint64 sys_$2(void);">>$kextemp;
    echo "\t[SYS_$2]\tsys_$2,">>$kfuntemp;
    echo "\t[SYS_$2]\t\"$2\",">>$kstrtemp;
}

entry	17	getcwd 
entry	23	dup	
entry	24	dup3
entry	25	fcntl	
entry	29	ioctl
entry   34	mkdirat
entry	35	unlinkat
entry   48	faccessat
entry	56	openat
entry	57	close
entry   59	pipe2
entry	61	getdents64
entry   62	lseek
entry	63	read
entry	64	write	
entry	65	readv
entry	66	writev	
entry   71	sendfile
entry	72	pselect6
entry   73	ppoll
entry	78	readlinkat
entry	79	fstatat 
entry	80	fstat 
entry	82	fsync
entry   88	utimensat
entry	93	exit	
entry	94	exit_group
entry	96	set_tid_address
entry   101	nanosleep
entry	103	setitimer
entry	113	clock_gettime	
entry	116	syslog	
entry   129 	kill
entry   131 	tgkill
entry	134	rt_sigaction
entry	135	rt_sigprocmask	
entry	139	rt_sigreturn
entry	144	setgid   
entry	146	setuid 
entry	160	uname 
entry	165	getrusage 
entry	166	umask
entry	172	getpid 
entry	173	getppid
entry	174	getuid
entry	175	geteuid
entry	176	getgid
entry	177	getegid
entry	178	gettid 
entry	179	sysinfo
entry	214	brk
entry	215	munmap 
entry	220	clone	
entry	221	execve
entry	222	mmap  
entry	226	mprotect
entry   227 msync
entry	260	wait4
entry	261	prlimit64
entry	276	renameat2



echo "};">>$kfuntemp;
echo "};">>$kstrtemp;

echo "#include \"include/syscall.h\"\n">>$ksys;
cat $kextemp>>$ksys
cat $kfuntemp>>$ksys
cat $kstrtemp>>$ksys
cat syscall/syscall.c>>$ksys
rm -f $kextemp $kfuntemp $kstrtemp
