usys=usrinit/usys.S
kextemp=syscall/ext.c
kfuntemp=syscall/fun.c
kstrtemp=syscall/str.c
ksys=src/syscall.c
sysnum=src/include/sysnum.h

echo "# generated by usys.pl - do not edit\n">>$usys;

echo "#include \"src/include/sysnum.h\"\n">>$usys;

echo "static uint64 (*syscalls[])(void) = {">>$kfuntemp;
echo "static char *sysnames[] = {">>$kstrtemp;

entry(){
    echo ".global $1">>$usys;
    echo "$1:">>$usys;
    echo "\tli a7, SYS_$1">>$usys;
    echo "\tecall">>$usys;
    echo "\tret">>$usys;
    echo "#define SYS_$1\t$2">>$sysnum
    echo "extern uint64 sys_$1(void);">>$kextemp;
    echo "\t[SYS_$1]\tsys_$1,">>$kfuntemp;
    echo "\t[SYS_$1]\t\"$1\",">>$kstrtemp;
}


entry	dup		23
entry	dup3		24
entry	openat		56
entry	read		63
entry	write		64
entry	exit		93
entry	rt_sigaction	134
entry	rt_sigreturn	139
entry	execve		221

echo "};">>$kfuntemp;
echo "};">>$kstrtemp;

echo "#include \"include/syscall.h\"\n">>$ksys;
cat $kextemp>>$ksys
cat $kfuntemp>>$ksys
cat $kstrtemp>>$ksys
cat syscall/syscall.c>>$ksys
rm -f $kextemp $kfuntemp $kstrtemp
